routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Mail;

Route::get('/', function () {
    if(!Auth::user()) {
        return view('auth.login');
    }
    else
        return redirect()->back();
});

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home')->middleware('admin');

Route::resource('ships', 'ShipController', ['only' => [
    'index', 'store', 'destroy', 'update'
]])->middleware('admin', 'auth');

Route::resource('ranks', 'RankController', ['only' => [
    'index', 'store', 'destroy', 'update'
]])->middleware('admin', 'auth');

Route::resource('crew', 'CrewController', ['only' => [
    'index', 'store', 'destroy', 'update'
]])->middleware('admin', 'auth');

Route::get('crew/{id}', 'CrewController@edit')->name('crew.edit');

Route::resource('notifications', 'NotificationController', ['only' => [
    'index', 'store', 'update', 'edit', 'show'
]])->middleware('auth');

Route::patch('save-password/{userId}', 'NotificationController@savePassword')->name('save.password');

Route::get('send-email/{userId}', 'CrewController@mail')->name('send.email');

app/Ship.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ship extends Model
{
    //
}

app/Http/Controllers/ShipController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\ShipAdd;
use App\Ship;
use App\Rank;

class ShipController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $ships = Ship::all();
        $ranks = Rank::all();
        return view('ships.home', compact('ships', 'ranks'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ShipAdd $request)
    {
        $ship = new Ship();

        $ship->name = $request->name;
        $ship->serial_number = $request->serial_number;

        if ($file = $request->file('profile_image')) {
            $destinationPath = 'images';
            $image = date('YmdHis') . "." . $file->getClientOriginalExtension();
            $file->move($destinationPath, $image);
            $ship->image = $image;
        }

        $ship->save();

        return redirect()->route('ships.index')->with('status', 'New ship added successfully!');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/ships/home.blade.php
@extends('layouts.app')

@section('content')
    @yield('content')
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Ships</h1>

    @if(session('status'))
        <div class="alert card mb-4 py-3 border-bottom-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <div class="card-body">
                {{ session('status') }}
            </div>
        </div>
    @endif

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <a href="#" data-toggle="modal" data-name="newShipModal" data-target="#newShipModal" class="btn btn-success btn-icon-split">
                    <span class="icon text-white-50">
                      <i class="fas fa-plus"></i>
                    </span>
                <span class="text">New Ship</span>
            </a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Serial number</th>
                        <th>Image</th>
                        <th>Add crew</th>
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <th>Name</th>
                        <th>Serial number</th>
                        <th>Image</th>
                        <th>Add crew</th>
                    </tr>
                    </tfoot>
                    <tbody>
                    @foreach($ships as $ship)
                        <tr>
                            <td class="align-middle">{{ $ship->name }}</td>
                            <td class="align-middle">{{ $ship->serial_number }}</td>
                            <td class="align-middle"><img class="img-fluid px-3 px-sm-4 mt-3 mb-4" width="170" src="../images/{{ $ship->image }}" alt=""></td>
                            <td class="align-middle">
                                <a data-toggle="modal" data-name="newCrewModal" data-id="{{ $ship->id }}" data-target="#newCrewModal" href="#newCrewModal" class="btn ship-id btn-success btn-circle btn-sm">
                                    <i class="fas fa-plus-circle"></i>
                                </a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <!-- Logout Modal-->
    <div class="modal fade" id="newShipModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">New ship</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">

                    <form class="user" action="{{ route('ships.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf

                        <div class="form-group">
                            <input id="name" type="text" class="form-control form-control-user @error('name') is-invalid @enderror" name="name" placeholder="Ship name" value="{{ old('name') }}" required>

                            @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>

                        <div class="form-group">
                            <input id="serial_number" type="text" maxlength="8" class="form-control form-control-user @error('serial_number') is-invalid @enderror" name="serial_number" placeholder="Serial number" value="{{ old('serial_number') }}" required>

                            @error('serial_number')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>

                        <div class="form-group">
                            <input id="profile_image" type="file" class="form-control form-control-user @error('profile_image') is-invalid @enderror" name="profile_image">

                            @error('profile_image')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-primary">Add</button>
                    </div>
                     </form>
            </div>
        </div>
    </div>

    <div class="modal fade" id="newCrewModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">New crew member</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">

                    <form class="user" action="{{ route('crew.store') }}" method="POST">
                        @csrf

                        <div class="form-group">
                            <input id="name" type="text" class="form-control form-control-user @error('name') is-invalid @enderror" name="name" placeholder="Crew name" value="{{ old('name') }}" required>

                            @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>

                        <div class="form-group">
                            <input id="surname" type="text" class="form-control form-control-user @error('surname') is-invalid @enderror" name="surname" placeholder="Crew surname" value="{{ old('surname') }}" required>

                            @error('surname')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>

                        <div class="form-group">
                            <input id="email" type="email" class="form-control form-control-user @error('email') is-invalid @enderror" name="email" placeholder="Email" value="{{ old('email') }}" required>

                            @error('email')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>

                        <div class="form-group">
                            <select name="rank" id="rank">
                                <option value="0">Please select rank...</option>
                                @foreach($ranks as $rank)
                                    <option value="{{ $rank->id }}">{{ $rank->name }}</option>
                                @endforeach
                            </select>
                            @error('rank')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>

                        <input type="hidden" name="ship_id" id="hiddenValue" value="" />

                </div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Add</button>
                </div>
                </form>
            </div>
        </div>
    </div>
@endsection